name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - 'website/**'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions: read-all

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      pages: write
    steps:
      - uses: actions/checkout@df4cb1cf17f246ab2dd04c67210db2d3e3ff53f7  # v6

      - uses: actions/setup-python@a26af69be951a213c5bd60f6403c5cad31e7cdb9  # v5
        with:
          python-version: '3.12'

      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Build site
        working-directory: website
        run: mkdocs build

      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b7192a  # v3
        with:
          path: website/site

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e5f8ac598231e27e  # v4
        id: deployment
